document.addEventListener("DOMContentLoaded", () => {
  const STARTER_CITIES = [
    "Jersey City NJ",
    "Hoboken NJ",
    "Weehawken NJ",
    "Fort Lee NJ",
    "Hackensack NJ",
    "Fairview NJ",
    "Saddle Brook NJ",
    "New Milford NJ",
    "Lyndhurst NJ",
    "Totowa NJ",
    "Montclair NJ",
    "Morristown NJ",
    "West Orange NJ",
    "Newark NJ"
  ];

  const VENUES = [
    {
      id: "grand-vin",
      name: "Grand Vin",
      city: "Hoboken",
      zip: "07030",
      address: "500 Grand St, Hoboken, NJ 07030",
      lat: 40.7486,
      lng: -74.0324,
      type: ["lounge", "restaurant", "wine bar", "italian"],
      crowd: "35–55+",
      crowdTags: ["30+", "40+", "mature crowd", "singles"],
      music: ["live music", "jazz", "acoustic"],
      bestNights: ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
      specials: ["Happy hour 5–7 PM", "Wine deals", "Live music Tue–Sat"],
      beerMax: 9,
      cocktailMax: 16,
      events: ["Tuesday jazz trio", "Thursday wine special", "Saturday live music"],
      desc: "Polished Hoboken pick with a stronger 30+ to 50+ crowd and grown-up vibe."
    },
    {
      id: "finnegans",
      name: "Finnegan's Pub",
      city: "Hoboken",
      zip: "07030",
      address: "734 Willow Ave, Hoboken, NJ 07030",
      lat: 40.7517,
      lng: -74.0333,
      type: ["pub", "tavern", "live music"],
      crowd: "30–50+",
      crowdTags: ["30+", "40+"],
      music: ["live music", "rock"],
      bestNights: ["Thursday", "Friday", "Saturday"],
      specials: ["Weekend live bands"],
      beerMax: 9,
      cocktailMax: 14,
      events: ["Friday cover band", "Saturday rock set"],
      desc: "Classic live-music pub with a broader grown-up crowd and easier vibe."
    },
    {
      id: "mills-tavern",
      name: "Mills Tavern",
      city: "Hoboken",
      zip: "07030",
      address: "125 Washington St, Hoboken, NJ 07030",
      lat: 40.7398,
      lng: -74.0306,
      type: ["restaurant", "cocktail bar", "lounge", "tavern"],
      crowd: "30–45+",
      crowdTags: ["30+", "singles", "dinner"],
      music: ["dj", "top 40"],
      bestNights: ["Thursday", "Friday", "Saturday"],
      specials: ["Dinner + cocktails", "Late-night bar crowd"],
      beerMax: 10,
      cocktailMax: 18,
      events: ["Friday dinner-to-drinks flow", "Saturday late crowd"],
      desc: "Good crossover pick when you want dinner first and nightlife after."
    },
    {
      id: "mcgoverns",
      name: "McGovern's Tavern",
      city: "Newark",
      zip: "07102",
      address: "58 New St, Newark, NJ 07102",
      lat: 40.7369,
      lng: -74.1706,
      type: ["tavern", "pub", "irish bar", "restaurant"],
      crowd: "30–60+",
      crowdTags: ["30+", "40+", "50+", "mature crowd"],
      music: ["live music", "rock", "irish music"],
      bestNights: ["Thursday", "Friday", "Saturday"],
      specials: ["Classic pub pours", "Occasional live sets"],
      beerMax: 8,
      cocktailMax: 13,
      events: ["Friday band night", "Saturday neighborhood crowd peak"],
      desc: "Historic Newark tavern with cheaper drinks, mature crowd, and classic pub energy."
    },
    {
      id: "bar-franco",
      name: "Bar Franco",
      city: "Montclair",
      zip: "07042",
      address: "5 Church St, Montclair, NJ 07042",
      lat: 40.8177,
      lng: -74.2102,
      type: ["lounge", "cocktail bar"],
      crowd: "30–45+",
      crowdTags: ["30+", "singles"],
      music: ["house", "dj", "lounge"],
      bestNights: ["Friday", "Saturday"],
      specials: ["Date-night vibe", "Select half-price cocktails"],
      beerMax: 10,
      cocktailMax: 17,
      events: ["Friday lounge DJ", "Saturday late cocktail crowd"],
      desc: "Stylish Montclair cocktail lounge with polished crowd energy and strong weekend appeal."
    },
    {
      id: "hudson-view",
      name: "Hudson View Lounge",
      city: "Weehawken",
      zip: "07086",
      address: "1200 Harbor Blvd, Weehawken, NJ 07086",
      lat: 40.7718,
      lng: -74.0153,
      type: ["lounge", "rooftop", "restaurant"],
      crowd: "30–50+",
      crowdTags: ["30+", "40+", "mature crowd"],
      music: ["house", "lounge", "dj"],
      bestNights: ["Friday", "Saturday"],
      specials: ["Skyline cocktail hour", "Waterfront vibe"],
      beerMax: 11,
      cocktailMax: 19,
      events: ["Friday skyline DJ", "Saturday cocktail crowd"],
      desc: "Scenic-style lounge profile for skyline drinks and older social energy."
    },
    {
      id: "son-cubano",
      name: "Son Cubano",
      city: "West New York",
      zip: "07093",
      address: "40-4 Riverwalk Pl, West New York, NJ 07093",
      lat: 40.7785,
      lng: -74.0078,
      type: ["restaurant", "lounge", "spanish", "latin"],
      crowd: "30–55+",
      crowdTags: ["30+", "40+", "mature crowd"],
      music: ["latin", "lounge", "dj"],
      bestNights: ["Thursday", "Friday", "Saturday", "Sunday"],
      specials: ["Waterfront dining", "Cocktail crowd"],
      beerMax: 9,
      cocktailMax: 17,
      events: ["Weekend lounge energy", "Latin dinner crowd"],
      desc: "Strong date-night and upscale Latin dining option with nightlife crossover."
    },
    {
      id: "fort-lee-social",
      name: "Fort Lee Social",
      city: "Fort Lee",
      zip: "07024",
      address: "204 Main St, Fort Lee, NJ 07024",
      lat: 40.8509,
      lng: -73.9701,
      type: ["bar", "lounge", "restaurant", "sports bar"],
      crowd: "30–45+",
      crowdTags: ["30+", "singles"],
      music: ["hip-hop", "house", "dj"],
      bestNights: ["Thursday", "Friday", "Saturday"],
      specials: ["Thursday DJ happy hour", "Late-night cocktails"],
      beerMax: 10,
      cocktailMax: 16,
      events: ["Thursday after-work social", "Saturday lounge crowd"],
      desc: "Flexible bar-lounge crossover for bridge-side meetups."
    },
    {
      id: "ventanas",
      name: "Ventanas Restaurant & Lounge",
      city: "Fort Lee",
      zip: "07024",
      address: "200 Park Ave, Fort Lee, NJ 07024",
      lat: 40.8516,
      lng: -73.9735,
      type: ["restaurant", "lounge", "steakhouse", "rooftop"],
      crowd: "30–60+",
      crowdTags: ["30+", "40+", "50+", "mature crowd"],
      music: ["lounge", "dj"],
      bestNights: ["Friday", "Saturday", "Sunday"],
      specials: ["Dinner and cocktails", "Event nights"],
      beerMax: 10,
      cocktailMax: 18,
      events: ["Upscale lounge nights", "Private event energy"],
      desc: "Big upscale restaurant-lounge destination in the Fort Lee area."
    },
    {
      id: "hackensack-live-room",
      name: "Hackensack Live Room",
      city: "Hackensack",
      zip: "07601",
      address: "55 Main St, Hackensack, NJ 07601",
      lat: 40.8862,
      lng: -74.0435,
      type: ["music venue", "bar", "live music"],
      crowd: "25–45+",
      crowdTags: ["20s", "30+", "40+"],
      music: ["live music", "rock", "country", "edm"],
      bestNights: ["Friday", "Saturday"],
      specials: ["Show-night drink bundles"],
      beerMax: 9,
      cocktailMax: 15,
      events: ["Friday live band schedule", "Saturday rotating event nights"],
      desc: "Good starter profile for people who care about the music first."
    },
    {
      id: "totowa-night-hub",
      name: "Totowa Night Hub",
      city: "Totowa",
      zip: "07512",
      address: "650 Union Blvd, Totowa, NJ 07512",
      lat: 40.9052,
      lng: -74.2238,
      type: ["bar", "restaurant", "sports bar"],
      crowd: "30–50+",
      crowdTags: ["30+", "40+"],
      music: ["top 40", "house", "dj"],
      bestNights: ["Friday", "Saturday"],
      specials: ["Friday cocktail special", "Saturday social room"],
      beerMax: 8,
      cocktailMax: 14,
      events: ["Friday crowd builder", "Saturday social night"],
      desc: "Starter Totowa option for a flexible social night without huge travel."
    },
    {
      id: "franklin-steakhouse",
      name: "Franklin Steakhouse",
      city: "Fair Lawn",
      zip: "07410",
      address: "318 Broadway, Fair Lawn, NJ 07410",
      lat: 40.9406,
      lng: -74.1186,
      type: ["steakhouse", "restaurant", "bar"],
      crowd: "35–65+",
      crowdTags: ["30+", "40+", "50+", "mature crowd"],
      music: ["lounge"],
      bestNights: ["Thursday", "Friday", "Saturday", "Sunday"],
      specials: ["Steakhouse dining", "Cocktail bar"],
      beerMax: 9,
      cocktailMax: 18,
      events: ["Dinner crowd", "Weekend social dining"],
      desc: "A strong upscale North Jersey steakhouse option with bar appeal."
    }
  ];

 
